const { SlashCommandBuilder, PermissionsBitField, EmbedBuilder } = require('discord.js');
const db = require('../../utils/db.js');
const { emojis, DEVELOPER_IDS } = require('../../utils/config.js');
const { error } = require('../../utils/embedFactory.js');
const { v4: uuidv4 } = require('uuid');

module.exports = {
    deploy: 'main', 
    data: new SlashCommandBuilder()
        .setName('generate_license')
        .setDescription('Developer Only: Generate a new license key.')
        .addStringOption(option => 
            option.setName('duration')
                .setDescription('Duration (e.g., "30", "365") or "permanent"/"lifetime"')
                .setRequired(true))
        .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator),

    async execute(interaction) {
        
        if (!DEVELOPER_IDS.includes(interaction.user.id)) {
            return interaction.editReply({ embeds: [error("Access Denied: Developer Only.")] });
        }

        const durationInput = interaction.options.getString('duration').toLowerCase();
        const licenseKey = `UPIECE-${uuidv4().toUpperCase()}`;
        
        let durationDays = null; 
        let durationText = "Permanent / Lifetime";

        if (durationInput !== 'permanent' && durationInput !== 'lifetime') {
            const days = parseInt(durationInput);
            if (isNaN(days) || days <= 0) {
              
                return interaction.editReply({ embeds: [error("Invalid duration. Use a number (days) or 'permanent'.")] });
            }
            durationDays = days;
            durationText = `${days} Days`;
        }

        try {
            await db.query(
                "INSERT INTO generated_licenses (license_key, duration_days, created_at) VALUES ($1, $2, $3)",
                [licenseKey, durationDays, Date.now()]
            );

            const embed = new EmbedBuilder()
                .setColor(0x2ECC71)
                .setTitle(`${emojis.success || '✅'} License Generated`)
                .addFields(
                    { name: 'Key', value: `\`${licenseKey}\``, inline: true },
                    { name: 'Duration', value: durationText, inline: true }
                )
                .setFooter({ text: `Generated by ${interaction.user.tag}` })
                .setTimestamp();

        
            await interaction.editReply({ embeds: [embed] });

        } catch (err) {
            console.error(err);
          
            await interaction.editReply({ embeds: [error("Database Error: Could not generate license.")] });
        }
    },
};